name: xoa-rtd

channels:
  - conda-forge

dependencies:
  - python>=3
  - cartopy
  - matplotlib
  - nbsphinx
  - pandas
  - scipy
  - xarray
  - xesmf
  - pip:
      - sphinx_rtd_theme
      - sphinx
      - nbsphinx
      - configobj

