name: xoa-rtd

channels:
  - conda-forge
  - defaults

dependencies:
  - appdirs
  - cartopy
  - fortran-compiler
  - ipython
  - jupyter_client
  - libgfortran
  - matplotlib-base
  - pandas
  - pip
  - python>=3
  #- scipy
  - xarray
  - xesmf
  - pip:
      - configobj
      - nbsphinx
      - sphinx
      - sphinx_rtd_theme
      - sphinx-argparse
      - sphinxcontrib-programoutput

