name: xoa-rtd

channels:
  - conda-forge

dependencies:
  - python>=3
  - pip
  - cartopy
  - matplotlib
  - pandas
  - scipy
  - xarray
  - xesmf
  - ipython
  - pip:
      - sphinx_rtd_theme
      - sphinx
      - nbsphinx
      - configobj
      - sphinxcontrib-programoutput
      - sphinx-argparse

