name: xoa-rtd

channels:
  - conda-forge

dependencies:
  - appdirs
  - cartopy
  - ipython
  - matplotlib
  - pandas
  - pip
  - python>=3
  - scipy
  - xarray
  - xesmf
  - pip:
      - configobj
      - nbsphinx
      - sphinx
      - sphinx_rtd_theme
      - sphinx-argparse
      - sphinxcontrib-programoutput

